// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CategoryFilter: typeof import('./src/components/CategoryFilter.vue')['default']
    copy: typeof import('./src/components/pages/top.page copy.vue')['default']
    'Create.page': typeof import('./src/components/pages/create.page.vue')['default']
    CreateIdea: typeof import('./src/components/CreateIdea.vue')['default']
    'Default.layout': typeof import('./src/components/layouts/default.layout.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCascaderPanel: typeof import('element-plus/es')['ElCascaderPanel']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    'Forgot.page': typeof import('./src/components/pages/forgot.page.vue')['default']
    'Home.layout': typeof import('./src/components/layouts/home.layout.vue')['default']
    'Home.page': typeof import('./src/components/pages/home.page.vue')['default']
    Idea: typeof import('./src/components/Idea.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    'Login.page': typeof import('./src/components/pages/login.page.vue')['default']
    'New.page': typeof import('./src/components/pages/new.page.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    'Register.page': typeof import('./src/components/pages/register.page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toggle: typeof import('./src/components/inputs/Toggle.vue')['default']
    'Top.page': typeof import('./src/components/pages/top.page.vue')['default']
  }
}
